export const appMeta = {
  product: 'OutageIQ',
  team: 'The NOC Squad',
  release: 'v1.0',
  refreshedAt: '2026-08-06T08:30:00.000Z',
};

export const demoUsers = [
  { username: 'rahul', password: 'outageiq-demo', displayName: 'Rahul K.', role: 'NOC Engineer' },
  { username: 'priya', password: 'outageiq-demo', displayName: 'Priya S.', role: 'Regional Ops Manager' },
];

export const outages = [
  {
    id: 'OUT-2026-0806-MUM-91',
    region: 'Mumbai',
    node: 'MUM-COR-19',
    severity: 'Critical',
    status: 'Open',
    priority: 'P1',
    impactScore: 94.2,
    subscribers: 4200000,
    complaints: 1842,
    complaintVelocity: 486,
    revenueExposure: '₹1.8 Cr/hr',
    duration: '4h 12m',
    rootCause: 'Core fiber cut after civil work strike',
    reachScore: 96,
    complaintScore: 95,
    revenueScore: 92,
    durationScore: 94,
  },
  {
    id: 'OUT-2026-0806-DEL-44',
    region: 'Delhi NCR',
    node: 'DEL-CORE-07',
    severity: 'Critical',
    status: 'Open',
    priority: 'P1',
    impactScore: 90.3,
    subscribers: 3800000,
    complaints: 1531,
    complaintVelocity: 423,
    revenueExposure: '₹1.4 Cr/hr',
    duration: '3h 05m',
    rootCause: 'Power instability at metro edge facility',
    reachScore: 90,
    complaintScore: 92,
    revenueScore: 88,
    durationScore: 91,
  },
  {
    id: 'OUT-2026-0806-BLR-12',
    region: 'Bangalore',
    node: 'BLR-SW-11',
    severity: 'High',
    status: 'Investigating',
    priority: 'P2',
    impactScore: 76.8,
    subscribers: 2900000,
    complaints: 940,
    complaintVelocity: 280,
    revenueExposure: '₹88 L/hr',
    duration: '2h 48m',
    rootCause: 'Microwave backhaul degradation during heavy rain',
    reachScore: 78,
    complaintScore: 77,
    revenueScore: 74,
    durationScore: 79,
  },
  {
    id: 'OUT-2026-0805-CHE-88',
    region: 'Chennai',
    node: 'CHE-EDGE-04',
    severity: 'High',
    status: 'In Progress',
    priority: 'P2',
    impactScore: 68.9,
    subscribers: 1800000,
    complaints: 710,
    complaintVelocity: 196,
    revenueExposure: '₹71 L/hr',
    duration: '5h 30m',
    rootCause: 'Aggregation switch memory pressure',
    reachScore: 68,
    complaintScore: 70,
    revenueScore: 66,
    durationScore: 81,
  },
  {
    id: 'OUT-2026-0805-HYD-55',
    region: 'Hyderabad',
    node: 'HYD-5G-18',
    severity: 'Medium',
    status: 'In Progress',
    priority: 'P3',
    impactScore: 54.4,
    subscribers: 2100000,
    complaints: 420,
    complaintVelocity: 101,
    revenueExposure: '₹44 L/hr',
    duration: '1h 55m',
    rootCause: '5G radio parameter drift after upgrade',
    reachScore: 55,
    complaintScore: 53,
    revenueScore: 52,
    durationScore: 58,
  },
  {
    id: 'OUT-2026-0804-JAI-29',
    region: 'Jaipur',
    node: 'JAI-TWR-03',
    severity: 'Low',
    status: 'Resolved',
    priority: 'P4',
    impactScore: 21.6,
    subscribers: 900000,
    complaints: 88,
    complaintVelocity: 22,
    revenueExposure: '₹9 L/hr',
    duration: '50m',
    rootCause: 'Access switch temperature alert',
    reachScore: 23,
    complaintScore: 21,
    revenueScore: 20,
    durationScore: 24,
  },
];

export const regions = [
  { region: 'Mumbai', score: 94, subscribers: '4.2M', tier: 'Premium', outages: 5 },
  { region: 'Delhi NCR', score: 90, subscribers: '3.8M', tier: 'Premium', outages: 4 },
  { region: 'Bangalore', score: 77, subscribers: '2.9M', tier: 'Premium', outages: 3 },
  { region: 'Chennai', score: 69, subscribers: '1.8M', tier: 'High', outages: 2 },
  { region: 'Hyderabad', score: 54, subscribers: '2.1M', tier: 'High', outages: 2 },
  { region: 'Pune', score: 41, subscribers: '1.4M', tier: 'Mid', outages: 1 },
];

export const analytics = {
  trend: [
    { date: 'Jul 30', outages: 8, avgImpact: 52 },
    { date: 'Jul 31', outages: 10, avgImpact: 57 },
    { date: 'Aug 01', outages: 11, avgImpact: 61 },
    { date: 'Aug 02', outages: 13, avgImpact: 65 },
    { date: 'Aug 03', outages: 15, avgImpact: 67 },
    { date: 'Aug 04', outages: 18, avgImpact: 72 },
    { date: 'Aug 05', outages: 20, avgImpact: 76 },
  ],
  complaintsByHour: [
    { hour: '06:00', complaints: 120 },
    { hour: '08:00', complaints: 240 },
    { hour: '10:00', complaints: 460 },
    { hour: '12:00', complaints: 630 },
    { hour: '14:00', complaints: 580 },
    { hour: '16:00', complaints: 760 },
    { hour: '18:00', complaints: 1010 },
    { hour: '20:00', complaints: 1240 },
  ],
};

export const queueSummary = {
  activeOutages: outages.filter((item) => item.status !== 'Resolved').length,
  criticalOutages: outages.filter((item) => item.severity === 'Critical').length,
  impactedCustomers: '2.48M',
  avgResolutionTime: '3h 42m',
  revenueAtRisk: '₹8.76 Cr',
};

export const weeklySummary = {
  totalOutages: 84,
  avgResolution: '3h 52m',
  revenueAtRisk: '₹42.3 Cr',
  slaCompliance: 84,
};